before_install:
  - gem install bundler

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.8
  - 2.2.4
  - 2.3.1
  - ruby-head
  - rbx
  - jruby

gemfile:
  - Gemfile
  - gemfiles/Gemfile.rails-3.2.x
  - gemfiles/Gemfile.rails-4.0.x
  - gemfiles/Gemfile.rails-4.1.x
  - gemfiles/Gemfile.rails-4.2.x
  - gemfiles/Gemfile.rails-5.0.x
  - gemfiles/Gemfile.rails-master

matrix:
  exclude:
    - rvm: 1.9.3
      gemfile: gemfiles/Gemfile.rails-master
    - rvm: 2.0.0
      gemfile: gemfiles/Gemfile.rails-master
    - rvm: 2.1.8
      gemfile: gemfiles/Gemfile.rails-master
    # activesupport has a dependency on json, which does not build on this version
    - rvm: ruby-head
      gemfile: gemfiles/Gemfile.rails-4.1.x.lock
    # activesupport has a dependency on json, which does not build on this version
    - rvm: ruby-head
      gemfile: gemfiles/Gemfile.rails-4.2.x.lock
  allow_failures:
    - rvm: 2.2
    - rvm: rbx
    - rvm: jruby
  fast_finish: true
